name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build --if-present
      - name: npm test
        run: npm test
      - name: make storybook
        run: npm run build-storybook
      - uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'https://react-sgh-$(git rev-parse --short HEAD).surge.sh'
          project: '.out'
          login: sina.ghadri.co@gmail.com
          token: ${{ secrets.SURGE_PASSWORD }}
      - uses: actions/checkout@v2
      - name: Add commit comment
        run: |
          GITCOMMITNAME=$(git rev-parse --short HEAD)
          DOCKERTAG=$(git describe --tags)
          title="react-sgh auto comment"
          body="on commit $GITCOMMITNAME  storybook: https://react-sgh-$GITCOMMITNAME.surge.sh "
          labels='workflow'
          json=$(jq -nc --arg l "$labels" --arg t "$title" --arg b "$body" '$l | split(", ") | {title: $t, body: $b, labels: .}')
          curl -sL  -X POST -d "$json" \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.SURGE_PASSWORD }}" \
            "https://api.github.com/repos/sinaghadrico/react-sgh/commits/$GITHUB_SHA/comments"
      - name: deploy
        run: |
          docker login docker.pkg.github.com --username sinaghadrico --password ${{ secrets.DOCKER_PASSWORD }}
          docker build . --file Dockerfile --tag docker.pkg.github.com/sinaghadrico/react-sgh/master:$(git describe --tags)
          docker push docker.pkg.github.com/sinaghadrico/react-sgh/master:$(git describe --tags)
